name: integration

on:
  push:
    branches:
      - 'master'
      - '[0-9].[0-9]+'  # release branches
    tags:
      - '*'
  workflow_dispatch:

jobs:
  tarantool:
    uses: tarantool/tarantool/.github/workflows/reusable_build.yml@master
    with:
      ref: ${{ github.sha }}
      os: ubuntu
      dist: focal

  vshard:
    needs: tarantool
    uses: tarantool/vshard/.github/workflows/reusable_testing.yml@master
    with:
      artifact_name: tarantool-ubuntu-focal-${{ github.sha }}

  cartridge:
    needs: tarantool
    uses: tarantool/cartridge/.github/workflows/reusable-backend-test.yml@master
    with:
      artifact_name: tarantool-ubuntu-focal-${{ github.sha }}

  expirationd:
    needs: tarantool
    uses: tarantool/expirationd/.github/workflows/reusable_testing.yml@ylobankov/add-reusable-testing-workflow  # Change to master before merge
    with:
      artifact_name: tarantool-ubuntu-focal-${{ github.sha }}
